### ISSUE TITLE
Keep the view leveled while turning

### ISSUE THREAD

**Issue by nico87** [simcodersdotcom/headshake#6]
This is to simulate the pilot keeping the head leveled with the horizon when the aircraft is banking.
It should be possible to activate/deactivate this option and also set its sensitiveness.

**Comment by markcellis** [comment]
I'm willing to do this enhancement but I could use a little input on how the sensitivity should work. As an example, if the plane is banked 20 degrees, should the head be kept perfectly level at 100% sensitivity? At 10% would the head roll be offset by 2 degrees which is 10% of the 20 degree bank? Should there be a limit on the bank, as an example, any bank over 20 degrees the head roll offset would only use a max of 20. I just made these numbers up but since I'm not a real world pilot yet I'm not sure what is typical pilot behavior .

Mark

**Comment by nico87** [comment]
Yes Mark, I would put a limit at around 20 degrees of bank since that's about the maximum the pilot's head may bank in flight.
The sensitivity may control both the bank for a given angle and the response time of the pilot moving his head. What do you think?

**Comment by markcellis** [comment]
The response time is a good idea, I had not thought of that.

 

Mark

**Comment by Denco96** [comment]
I would really much like to see this if possible. This has been implemented into ezdok v2 and works really well. It would be nice to have an option for how much the head banks. 

https://www.youtube.com/watch?v=G6OcnV3ols8

**Comment by markcellis** [comment]
It looks like Althar93 has been doing some stuff. Is he planning on making this enhancement. I’m still willing to do it but it may be a while before I get to it.

 

Mark

**Comment by Althar93** [comment]
@markcellis You can go ahead and pick this up whenever you feel like it - this is not something I have started looking at yet so if implementing this feature strikes your fancy, be my guest. My current work schedule makes it difficult for me to contribute anything at the moment so you should have a good head start.

**Comment by nico87** [comment]
@Denco96 I think you can go on and implement this issue. ;-)

**Comment by rdrehmer** [comment]
I signed up just to leave this here:http://developer.x-plane.com/2017/06/roll-over-beethoven-and-pilots-head/

Hope it helps!
